### ISSUE TITLE
In-depth queue update (Will be updated)

### ISSUE THREAD

**Issue by memorisecodead** [f1nal3/Juniorgram#669]
## Idea: 
The server is one of the centers of the application, which must do its job stably. Linking the server to the "clients" means that the server must stably receive and send packets of messages. The server also processes messages.
It is necessary to make sure that the queue works correctly in possible cases of its use. (which ones? this will be identified and added later).
## Goals: 
- To find and eliminate the weaknesses of the queue. 
- Trying to improve performance of the queue.
- Write tests to ensure that the queue works correctly. 
## Workflow:
- [ ] Investigate queue behavior under load in single-threaded and multithreaded modes. 
**Load the queue. (try to "Break")**
- [ ] Identify possible deficiencies.
- [ ] Fix possible vulnerabilities.
- [ ] Improve the queue. 
- [ ] Write tests for the queue.
