### ISSUE TITLE
Aggregate Service Core

### ISSUE THREAD

**Issue by f1nal3** [f1nal3/Juniorgram#670]
## Description:
In order to make creating services simple we need to separate the common parts into a new CMake target - Service.Core.
This target consists of everything that a service might need: Network, Argument Parsing, Utility functions, Data Access etc.
Directories should be reworked accordingly.

## Acceptance Criteria:

- [ ] All the code that is used by the Service.Core is located in the according directory. 
- [ ] The rest of the code is deleted. As well as their tests that are no longer needed.
- [ ] A commit on the dev branch should be tagged, marking it has all the code that was considered useless.
- [ ] A static library named "Service.Core" compiles.
- [ ] All the tests pass.
